var annotated_dup =
[
    [ "AssetIO", "d0/d86/namespaceAssetIO.html", [
      [ "ComInit", "df/d63/structAssetIO_1_1ComInit.html", "df/d63/structAssetIO_1_1ComInit" ]
    ] ],
    [ "msg", "d5/d64/namespacemsg.html", [
      [ "BoardMeta", "d1/d9f/structmsg_1_1BoardMeta.html", "d1/d9f/structmsg_1_1BoardMeta" ],
      [ "InboundRaw", "d2/d0a/structmsg_1_1InboundRaw.html", "d2/d0a/structmsg_1_1InboundRaw" ],
      [ "MarkerMeta", "d7/d3a/structmsg_1_1MarkerMeta.html", "d7/d3a/structmsg_1_1MarkerMeta" ],
      [ "NetEvent", "d6/d0f/structmsg_1_1NetEvent.html", "d6/d0f/structmsg_1_1NetEvent" ],
      [ "ReadyMessage", "da/d01/structmsg_1_1ReadyMessage.html", "da/d01/structmsg_1_1ReadyMessage" ]
    ] ],
    [ "ActiveBoard", "dc/d4e/structActiveBoard.html", null ],
    [ "ApplicationHandler", "d8/d43/classApplicationHandler.html", "d8/d43/classApplicationHandler" ],
    [ "Board", "db/d27/structBoard.html", "db/d27/structBoard" ],
    [ "BoardImageData", "dc/d36/structBoardImageData.html", "dc/d36/structBoardImageData" ],
    [ "BoardManager", "d9/dff/classBoardManager.html", "d9/dff/classBoardManager" ],
    [ "Camera", "d1/df0/classCamera.html", "d1/df0/classCamera" ],
    [ "ChatGroupModel", "d5/da8/structChatGroupModel.html", "d5/da8/structChatGroupModel" ],
    [ "ChatManager", "d7/dc6/classChatManager.html", "d7/dc6/classChatManager" ],
    [ "ChatMessageModel", "dd/d01/structChatMessageModel.html", "dd/d01/structChatMessageModel" ],
    [ "DebugConsole", "da/d4c/classDebugConsole.html", null ],
    [ "DebugToggle", "d5/d43/structDebugToggle.html", "d5/d43/structDebugToggle" ],
    [ "DirectoryWindow", "d1/d07/classDirectoryWindow.html", "d1/d07/classDirectoryWindow" ],
    [ "DragState", "d3/ddf/structDragState.html", "d3/ddf/structDragState" ],
    [ "FogOfWar", "d3/d8f/structFogOfWar.html", null ],
    [ "GameTable", "de/dca/structGameTable.html", "de/dca/structGameTable" ],
    [ "GameTableManager", "da/d28/classGameTableManager.html", "da/d28/classGameTableManager" ],
    [ "Grid", "d5/d78/structGrid.html", "d5/d78/structGrid" ],
    [ "Identifier", "df/d1d/structIdentifier.html", "df/d1d/structIdentifier" ],
    [ "IdentityManager", "d8/d43/classIdentityManager.html", "d8/d43/classIdentityManager" ],
    [ "ImGuiToaster", "d8/db3/classImGuiToaster.html", "d8/db3/classImGuiToaster" ],
    [ "IndexBuffer", "dd/df7/classIndexBuffer.html", "dd/df7/classIndexBuffer" ],
    [ "InputTextWrapCtx", "d4/d8e/structInputTextWrapCtx.html", "d4/d8e/structInputTextWrapCtx" ],
    [ "Logger", "db/d67/classLogger.html", "db/d67/classLogger" ],
    [ "MapFBO", "da/d20/structMapFBO.html", "da/d20/structMapFBO" ],
    [ "MarkdownRenderer", "de/d26/classMarkdownRenderer.html", "de/d26/classMarkdownRenderer" ],
    [ "MarkerComponent", "df/d84/structMarkerComponent.html", "df/d84/structMarkerComponent" ],
    [ "MessageQueue", "d3/df0/classMessageQueue.html", "d3/df0/classMessageQueue" ],
    [ "Moving", "de/dc8/structMoving.html", "de/dc8/structMoving" ],
    [ "NetworkManager", "d6/d6f/classNetworkManager.html", "d6/d6f/classNetworkManager" ],
    [ "NetworkUtilities", "dd/d71/classNetworkUtilities.html", null ],
    [ "Note", "db/dfe/structNote.html", "db/dfe/structNote" ],
    [ "NoteComponent", "d4/ddb/structNoteComponent.html", "d4/ddb/structNoteComponent" ],
    [ "NoteEditorUI", "dc/de9/classNoteEditorUI.html", "dc/de9/classNoteEditorUI" ],
    [ "Notes", "d5/d03/structNotes.html", "d5/d03/structNotes" ],
    [ "NotesManager", "d6/d22/classNotesManager.html", "d6/d22/classNotesManager" ],
    [ "NotesManagerConfig", "db/de3/structNotesManagerConfig.html", "db/de3/structNotesManagerConfig" ],
    [ "Panning", "d8/d15/structPanning.html", "d8/d15/structPanning" ],
    [ "PathManager", "d8/dec/classPathManager.html", null ],
    [ "PeerIdentity", "d3/dcd/structPeerIdentity.html", "d3/dcd/structPeerIdentity" ],
    [ "PeerLink", "db/d08/classPeerLink.html", "db/d08/classPeerLink" ],
    [ "PendingImage", "d9/d6c/structPendingImage.html", "d9/d6c/structPendingImage" ],
    [ "Position", "d0/df4/structPosition.html", "d0/df4/structPosition" ],
    [ "Renderer", "d1/d52/classRenderer.html", "d1/d52/classRenderer" ],
    [ "Serializer", "db/d4b/classSerializer.html", null ],
    [ "Shader", "d9/d69/classShader.html", "d9/d69/classShader" ],
    [ "ShaderProgramSource", "dc/d76/structShaderProgramSource.html", "dc/d76/structShaderProgramSource" ],
    [ "SignalingClient", "d9/d85/classSignalingClient.html", "d9/d85/classSignalingClient" ],
    [ "SignalingServer", "d6/d0b/classSignalingServer.html", "d6/d0b/classSignalingServer" ],
    [ "Size", "d7/d02/structSize.html", "d7/d02/structSize" ],
    [ "Texture", "d6/d97/classTexture.html", "d6/d97/classTexture" ],
    [ "TextureComponent", "d5/d7f/structTextureComponent.html", "d5/d7f/structTextureComponent" ],
    [ "UPnPManager", "db/d12/classUPnPManager.html", null ],
    [ "VertexArray", "da/dd7/classVertexArray.html", "da/dd7/classVertexArray" ],
    [ "VertexBuffer", "d7/d72/classVertexBuffer.html", "d7/d72/classVertexBuffer" ],
    [ "VertexBufferElement", "dc/dab/structVertexBufferElement.html", "dc/dab/structVertexBufferElement" ],
    [ "VertexBufferLayout", "d2/dd9/classVertexBufferLayout.html", "d2/dd9/classVertexBufferLayout" ],
    [ "Visibility", "da/d89/structVisibility.html", "da/d89/structVisibility" ]
];